mode: stg
env: stg
appName: ingestor
domain: stg-ingestor-svc.default.svc.cluster.local
readers:
  presto:
    schema: data
    port: 8042
writers:
  grpc:
    port: 8043
storage:
  dir: /data
tables:
  events:
    ttl: 3600
    hashBy: event
    sortBy: ingested_at
    schema: "gcs://k8s-online-stg-configs/ingestor/schema.yaml"
    streams:
      - pubsub:
          project: "airasia-opdatalake-stg"
          topic: "talaria-test"
          encoder: "json"
    compact:
      interval: 60
      nameFunc: "gcs://k8s-online-stg-configs/ingestor/name.lua"
      sinks:
        - gcs:
            bucket: "airasia-opdatalake-stg-datalake"
            prefix: "sink/"
            encoder: "orc"
        - bigquery:
            project: "airasia-opdatalake-stg"
            dataset: "eventlog"
            table: "events"
            encoder: "block"
            # do not use the same file for another sink. Create a new one.
            filter: "gcs://k8s-online-stg-configs/ingestor/filters/cors.lua"
        - talaria:
            endpoint: "query.opdl.stg.data.airasiainternal.net:8043"
            encoder: "orc"
computed:
  - name: ingested_at
    func: "make://timestamp"
  - name: event_id
    func: "make://identifier"
  - name: ctx
    type: json
    func: "gcs://k8s-online-stg-configs/ingestor/columns/ctx.lua"
  - name: ingested_by
    type: string
    func: "gcs://k8s-online-stg-configs/ingestor/columns/ingested_by.lua"
