name: Test
on: [push, pull_request]
env:
  PROJECT: "github.com/kelindar/talaria"
  GO111MODULE: "on"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run tests
        run: |
          go test -race ./...
